### ISSUE TITLE
Not working with ownCloud 8.1

### ISSUE THREAD

**Issue by phiL0co** [icewind1991/owncloud-markdown#14]
Hi!
I just updated from OC 8.0.4 to 8.1 and installed the master of owncloud-markdown.
In OC 8.0.4 it worked flawlessly. 
Now I can activate the app, but the editor does not show up when I open a *.md file.
Is the app supposed to work with 8.1 or not yet?

THX in advance!

Best regards
phiL0co

**Comment by tristan-k** [comment]
Same for me.

**Comment by v1r0x** [comment]
Same here.

I found the problem and a workaround (not really good...).
The problem is this line:
https://github.com/icewind1991/owncloud-markdown/blob/master/js/editor.js#L140
If I execute this block in firefox (firebug console) I get the following error:
*TypeError: window.showFileEditor(...) is undefined*
But if I open the text file and then execute this part
https://github.com/icewind1991/owncloud-markdown/blob/master/js/editor.js#L141-L142
it works as in 8.0.4

I'm not good in javascript and owncloud at all, so I don't know how to fix it, but I hope this helps.

**Comment by shrimpza** [comment]
Changes made to the [files_texteditor](https://github.com/owncloud/files_texteditor/) plugin, in particular owncloud/files_texteditor@8440ecf4699ee6da2454cfd54f4eb70ffc88ff24 - which has removed the return result, thereby breaking the callback chain expected.

I don't see a way around this without restoring the original return result in the text editor plugin, aside from polling the editor until it's ready, which seems like a *really* bad idea.

**Comment by idef1x** [comment]
Too bad it doesn't work with 8.1..(can't even enable it)...it looked promising and couldn't find an alternative yet :'(

**Comment by kpn3m0** [comment]
+1
If anyone finds an alternative or a fix please post here.

**Comment by icewind1991** [comment]
Fixed with c068723e0fe4ab856383faaf0a8bc7f0198f3262

**Comment by idef1x** [comment]
sadly when I enable it my whole owncloud stops functioning

**Comment by v1r0x** [comment]
Thanks for the fix, but I have a similar problem. Most of the apps won't work anymore.

**Comment by origpumu** [comment]
Sadly still not working. Editor opens as a normal texteditor without the preview in formated letters.

**Comment by jbtrystram** [comment]
Same here. opens as a normal text editor

**Comment by rabenimmermehr** [comment]
Same here, 
Owncloud 8.1, Google Chrome on Windows 10 (If that makes any difference)
